import {
  Calendar,
  MapPin,
  Clock,
  Monitor,
  Phone,
  Mail,
  Instagram,
  ShieldCheck,
  Cog,
  Lightbulb,
  Users,
  MessageSquare,
  ClipboardList,
  ArrowRight,
  BarChart,
  Briefcase,
  GitBranch,
  Database,
  Server,
  Workflow,
  FileText,
  Book,
  GraduationCap,
  Globe,
  Gamepad2,
  Camera,
  Music,
  Target,
  Medal,
  Star,
  Check,
  Smartphone,
  Award,
  Link,
  Github,
  Linkedin,
} from "lucide-react";
import { WhatsApp } from "@/components/ui/whatsapp";

const iconMap: { [key: string]: React.ElementType } = {
  calendario: Calendar,
  pin_de_ubicacion: MapPin,
  reloj: Clock,
  monitor_de_computadora: Monitor,
  auricular_de_telefono: Phone,
  logotipo_whatsapp: WhatsApp,
  sobre_de_correo: Mail,
  logotipo_instagram: Instagram,
  "escudo_con_marca_de_verificacion_(check)": ShieldCheck,
  engranajes_interconectados: Cog,
  "cabeza_humana_con_bombilla_de_luz": Lightbulb,
  grupo_de_personas: Users,
  burbujas_de_dialogo: MessageSquare,
  portapapeles_con_lista: ClipboardList,
  flechas_cruzadas_entrelazadas: ArrowRight,
  "grafico_de_barras_con_flecha_ascendente": BarChart,
  maletin_de_trabajo: Briefcase,
  engranaje: Cog,
  "nodos_de_ramificacion_(git)": GitBranch,
  "monitor_y_telefono_movil": Smartphone,
  "discos_apilados_(cilindro)": Database,
  "nodos_de_conexion_en_red": Link,
  rack_de_servidor: Server,
  "cabeza_con_engranajes_o_ideas": Workflow,
  documento_de_texto: FileText,
  "documento_con_tabla": Book,
  birrete_de_graduacion: GraduationCap,
  globo_terraqueo: Globe,
  mando_de_consola: Gamepad2,
  camara_fotografica: Camera,
  nota_musical: Music,
  "diana_de_tiro_al_blanco_con_flecha": Target,
  "portapapeles_con_diana_y_flecha": Award,
  "medalla_con_estrella": Medal,
  estrella: Star,
  "marca_de_verificacion_naranja_(check)": Check,
  silueta_de_usuario: Users,
  github: Github,
  linkedin: Linkedin
};

export const getIcon = (name: string) => {
  const Icon = iconMap[name];
  return Icon ? <Icon /> : null;
};
