import { useState } from "react";
import { Link } from "react-router-dom";
import { Activity, ArrowLeft, ArrowRight, BarChart3, Bell, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, Heart, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Package, Pause, Play, Plus, Search, Send, Settings2, ShoppingBag, Sparkles, TrendingUp, Users, WandSparkles, Zap } from "lucide-react";
import "./demo-experience.css";

type Kind = "commerce" | "analytics" | "management" | "booking" | "automation" | "social";

const brands = {
  commerce:["NÓMADA","Tienda","Colecciones","Journal"], analytics:["PULSE","Overview","Revenue","Customers"],
  management:["ORBIT","Mi trabajo","Proyectos","Equipo"], booking:["MESA","Reservar","Menú","El lugar"],
  automation:["FLOWSTATE","Workflows","Agentes","Runs"], social:["BEACON","Studio","Calendario","Analytics"],
};

const Shell=({kind,children}:{kind:Kind;children:React.ReactNode})=><div className={`dx dx-${kind}`}>
  <header className="dx-top"><b><i>{brands[kind][0][0]}</i>{brands[kind][0]}</b><nav>{brands[kind].slice(1).map((x,i)=><button className={i?"":"on"} key={x}>{x}</button>)}</nav><div><button aria-label="Notificaciones"><Bell size={16}/></button><Link to="/#projects"><ArrowLeft size={15}/> Portfolio</Link><button className="dx-menu"><Menu size={18}/></button></div></header>{children}</div>;

const Commerce=()=>{
  const [cart,setCart]=useState(0),[filter,setFilter]=useState("Todo");
  const products=[["Trail Shell 02","Abrigos","184","https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80"],["Terra Pack 28L","Equipamiento","129","https://images.unsplash.com/photo-1553062407-98eeb64c6a45?auto=format&fit=crop&w=900&q=80"],["Ridge Runner","Calzado","148","https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"]];
  return <Shell kind="commerce"><main className="shop"><section className="shop-hero"><div><small>COLECCIÓN / 2026</small><h1>Diseñado para<br/>salir del mapa.</h1><p>Equipamiento técnico para moverse ligero, llegar más lejos y dejar que el camino haga el resto.</p><button onClick={()=>document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})}>Explorar colección <ArrowRight size={17}/></button></div><img src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85" alt="Montañas"/></section><section id="catalog" className="catalog"><header><div><small>EQUIPO ESENCIAL</small><h2>Listos para el próximo desvío.</h2></div><button onClick={()=>setCart(0)}><ShoppingBag size={16}/> Bolsa <b>{cart}</b></button></header><div className="pills">{["Todo","Abrigos","Equipamiento","Calzado"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="products">{products.filter(x=>filter==="Todo"||x[1]===filter).map(x=><article key={x[0]}><div><img src={x[3]} alt={x[0]}/><button><Heart size={18}/></button></div><small>{x[1]}</small><h3>{x[0]} <b>US$ {x[2]}</b></h3><button onClick={()=>setCart(c=>c+1)}>Agregar a la bolsa <Plus size={15}/></button></article>)}</div></section></main></Shell>
};

const Analytics=()=>{
  const bars=[44,63,48,72,58,82,75,94,68,87,76,98];
  return <Shell kind="analytics"><main className="dash"><header className="page-head"><div><small>LUNES, 27 JUL</small><h1>Buen día, Lucio.</h1><p>Tu negocio creció un 18,4% este mes.</p></div><button><CalendarDays size={15}/> Últimos 30 días <ChevronDown size={14}/></button></header><section className="metrics">{[["Ingresos netos","$84.240","+18,4%"],["Pedidos","1.429","+12,1%"],["Ticket promedio","$58,95","+4,2%"],["Devoluciones","2,4%","-0,8%"]].map(x=><article key={x[0]}><span>{x[0]}<MoreHorizontal size={16}/></span><b>{x[1]}</b><small>{x[2]} <em>vs. período anterior</em></small></article>)}</section><section className="data-grid"><article className="chart"><header><div><span>Ingresos</span><b>$84.240</b></div><small><i/> Este período</small></header><div className="bars">{bars.map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></article><article className="channels"><b>Canales de venta</b><div className="donut"><span>1.429<small>ventas</small></span></div>{[["Tienda online","62%"],["Marketplace","24%"],["Retail","14%"]].map(x=><p key={x[0]}>{x[0]}<b>{x[1]}</b></p>)}</article></section><section className="activity"><header><b>Actividad reciente</b><small>Actualizado hace 2 min</small></header>{[["#1048","Camila Rossi","$142,00","Completado"],["#1047","Mateo Silva","$89,50","Procesando"],["#1046","Julia Gómez","$274,20","Completado"]].map(x=><div key={x[0]}>{x.map(y=><span key={y}>{y}</span>)}</div>)}</section></main></Shell>
};

const Management=()=>{
  const [selected,setSelected]=useState("");
  const cols=[["POR HACER",["Onboarding de comercios"]],["EN CURSO",["Sistema de diseño v3","Migración de infraestructura"]],["EN REVISIÓN",["Nueva experiencia de checkout"]],["LISTO",["Nueva página de precios"]]];
  return <Shell kind="management"><main className="orbit"><aside><button><Search size={16}/> Buscar <kbd>⌘ K</kbd></button><small>WORKSPACE</small><button><LayoutDashboard size={16}/> Overview</button><button className="on"><Package size={16}/> Proyectos</button><button><Users size={16}/> Equipo</button><small>FAVORITOS</small><button><i/> Plataforma web</button><button><i/> Mobile app</button></aside><section><header className="page-head"><div><small>PROYECTOS / PRODUCTO</small><h1>Plataforma web</h1><p>Todo lo necesario para llegar a producción.</p></div><button><Plus size={15}/> Nueva tarea</button></header><nav className="views"><button className="on">Board</button><button>Lista</button><button>Timeline</button></nav><div className="kanban">{cols.map((col,ci)=><div key={col[0] as string}><header><b><i/>{col[0]}</b><span>{col[1].length}</span></header>{(col[1] as string[]).map((task,ti)=><button className={selected===task?"selected":""} onClick={()=>setSelected(task)} key={task}><small>{["Growth","Diseño","Dev","Producto"][ci]}</small><h3>{task}</h3><div className="progress"><i style={{width:`${40+ti*22+ci*12}%`}}/></div><footer><span><Clock3 size={12}/> {ci+27} Jul</span><b>LC</b></footer></button>)}<button className="add"><Plus size={14}/> Agregar tarea</button></div>)}</div></section></main></Shell>
};

const Booking=()=>{
  const [guests,setGuests]=useState(2),[time,setTime]=useState("21:00"),[done,setDone]=useState(false);
  return <Shell kind="booking"><main className="mesa"><section><img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=85" alt="Restaurante"/><div><small>COCINA DE ESTACIÓN · BUENOS AIRES</small><h1>Una mesa.<br/>Una pausa.<br/>Algo para recordar.</h1><p>Producto, fuego y tiempo. Lo demás sobra.</p></div></section><section className="reserve">{done?<div className="confirmed"><i><Check size={28}/></i><small>RESERVA CONFIRMADA</small><h2>Nos vemos el viernes.</h2><p>Mesa para {guests} a las {time}. Enviamos los detalles a tu correo.</p><b>31 <span>JUL<br/>2026</span></b><button onClick={()=>setDone(false)}>Modificar reserva</button></div>:<><small>RESERVAS</small><h2>Tu mesa te espera.</h2><p>Elegí cuándo venir. Nosotros hacemos el resto.</p><label>FECHA<button><CalendarDays size={17}/> Vie, 31 de julio <ChevronDown size={14}/></button></label><label>PERSONAS<div className="stepper"><button onClick={()=>setGuests(Math.max(1,guests-1))}>−</button><b>{guests} personas</b><button onClick={()=>setGuests(guests+1)}>+</button></div></label><label>HORARIO<div className="times">{["19:30","20:00","20:30","21:00","21:30","22:00"].map(x=><button className={time===x?"on":""} onClick={()=>setTime(x)} key={x}>{x}</button>)}</div></label><button className="confirm" onClick={()=>setDone(true)}>Confirmar reserva <ArrowRight size={17}/></button></>}</section></main></Shell>
};

const Automation=()=>{
  const [running,setRunning]=useState(true),[runs,setRuns]=useState(1248);
  return <Shell kind="automation"><main className="flow"><aside><button className="new"><Plus size={16}/> Nuevo workflow</button><button className="on"><Zap size={16}/> Workflows</button><button><WandSparkles size={16}/> Agentes IA</button><button><Activity size={16}/> Ejecuciones</button><button><Settings2 size={16}/> Conexiones</button><div><small>USO DEL MES</small><i><b/></i><strong>6.842 / 10.000 runs</strong></div></aside><section><header className="flow-head"><div><small>● EN PRODUCCIÓN</small><h1>Revenue intelligence</h1><p>Califica oportunidades y prepara el siguiente paso automáticamente.</p></div><div><button onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?"Pausar":"Activar"}</button><button onClick={()=>{setRuns(runs+1);setRunning(true)}}><Play size={15}/> Ejecutar ahora</button></div></header><div className="flow-metrics">{[["Ejecuciones",runs.toLocaleString("es-AR"),"+14,2%"],["Tasa de éxito","98,7%","+1,1%"],["Tiempo ahorrado","74 h","este mes"],["Costo por run","$0,018","-8,4%"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><section className="canvas"><header>Workflow <span>−　85%　+</span></header><div className="nodes">{[["TRIGGER","Nuevo lead en CRM","HubSpot",Zap],["AGENTE IA","Investigar la cuenta","GPT-5 · Web search",Sparkles],["ACCIÓN","Crear briefing","Notion",Send],["ACCIÓN","Avisar al equipo","Slack",MessageCircle]].map((x,i)=>{const Icon=x[3] as typeof Zap;return <><article key={x[1] as string}><Icon size={18}/><div><small>{x[0] as string}</small><b>{x[1] as string}</b><em>{x[2] as string}</em></div><CheckCircle2 size={15}/></article>{i<3&&<i className="line"/>}</>})}</div></section></section></main></Shell>
};

const Social=()=>{
 const [liked,setLiked]=useState(false);
 return <Shell kind="social"><main className="beacon"><header className="page-head"><div><small>CONTENT STUDIO</small><h1>Todo lo que publicás.<br/>Una sola vista.</h1></div><button><Plus size={15}/> Crear contenido</button></header><section className="social-cards"><article className="audience"><span>Audiencia total</span><b>248.6K</b><small><TrendingUp size={13}/> 12.8% este mes</small><div>{[22,34,30,46,40,55,48,66,58,72,64,84,78,92].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></article><article className="reach">{[["Alcance","1.8M","+24.6%"],["Interacciones","94.2K","+18.1%"],["Engagement","5.2%","+0.8%"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</article><article className="best"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=700&q=80" alt="Estudio"/><div><small>MEJOR POST · INSTAGRAM</small><p>Las ideas crecen cuando encuentran espacio.</p><button className={liked?"liked":""} onClick={()=>setLiked(!liked)}><Heart size={15} fill={liked?"currentColor":"none"}/> 12.4K</button></div></article></section><section className="calendar"><header><div><h2>Próximas publicaciones</h2><p>Esta semana · 8 contenidos programados</p></div><button>Todos <ChevronDown size={13}/></button></header><div>{["LUN 27","MAR 28","MIÉ 29","JUE 30","VIE 31"].map((d,i)=><section key={d}><small>{d}</small>{i<3?<article><span>{["09:30","12:15","18:00"][i]}</span><i/><b>{["Behind the scenes","5 ideas para diseñar mejor","Weekly product note"][i]}</b><em>{["Reel","Carrusel","Post"][i]}</em></article>:<button><Plus size={16}/></button>}</section>)}</div></section></main></Shell>
};

export const DemoExperience=({kind}:{kind:Kind})=>kind==="commerce"?<Commerce/>:kind==="analytics"?<Analytics/>:kind==="management"?<Management/>:kind==="booking"?<Booking/>:kind==="automation"?<Automation/>:<Social/>;
