import { Fragment, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, ArrowLeft, ArrowRight, BarChart3, Bell, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, Heart, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Package, Pause, Play, Plus, Search, Send, Settings2, ShoppingBag, Sparkles, TrendingUp, Users, WandSparkles, Zap } from "lucide-react";
import "./demo-experience.css";

type Kind = "commerce" | "analytics" | "management" | "booking" | "automation" | "social";

const brands = {
  commerce:["NÓMADA","Tienda","Colecciones","Journal"], analytics:["PULSE","Overview","Revenue","Customers"],
  management:["ORBIT","Mi trabajo","Proyectos","Equipo"], booking:["MESA","Reservar","Menú","El lugar"],
  automation:["FLOWSTATE","Workflows","Agentes","Runs"], social:["BEACON","Studio","Calendario","Analytics"],
};

const Shell=({kind,children}:{kind:Kind;children:React.ReactNode})=>{
  const [active,setActive]=useState(0),[notice,setNotice]=useState("");
  const select=(index:number,label:string)=>{setActive(index);setNotice(`${label}: vista actualizada`);window.setTimeout(()=>setNotice(""),1800)};
  return <div className={`dx dx-${kind}`}>
    <header className="dx-top"><b><i>{brands[kind][0][0]}</i>{brands[kind][0]}</b><nav>{brands[kind].slice(1).map((x,i)=><button className={active===i?"on":""} onClick={()=>select(i,x)} key={x}>{x}</button>)}</nav><div><button onClick={()=>setNotice("No tenés notificaciones pendientes")} aria-label="Notificaciones"><Bell size={16}/></button><Link to="/#projects"><ArrowLeft size={15}/> Portfolio</Link><button onClick={()=>setNotice("Menú de navegación")} className="dx-menu"><Menu size={18}/></button></div></header>{children}{notice&&<div className="dx-toast"><CheckCircle2 size={16}/>{notice}</div>}</div>
};

const Commerce=()=>{
  const products=[{id:1,name:"Trail Shell 02",cat:"Abrigos",price:184,img:"https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80"},{id:2,name:"Terra Pack 28L",cat:"Equipamiento",price:129,img:"https://images.unsplash.com/photo-1622260614153-03223fb72052?auto=format&fit=crop&w=900&q=80"},{id:3,name:"Ridge Runner",cat:"Calzado",price:148,img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"}];
  const [cart,setCart]=useState<Record<number,number>>({}),[filter,setFilter]=useState("Todo"),[open,setOpen]=useState(false),[saved,setSaved]=useState<number[]>([]),[checkout,setCheckout]=useState(false);
  const count=Object.values(cart).reduce((a,b)=>a+b,0), subtotal=products.reduce((sum,p)=>sum+p.price*(cart[p.id]||0),0);
  const change=(id:number,amount:number)=>setCart(current=>{const next={...current,[id]:Math.max(0,(current[id]||0)+amount)};if(!next[id])delete next[id];return next});
  return <Shell kind="commerce"><main className="shop"><section className="shop-hero"><div><small>COLECCIÓN / 2026</small><h1>Diseñado para<br/>salir del mapa.</h1><p>Equipamiento técnico para moverse ligero, llegar más lejos y dejar que el camino haga el resto.</p><button onClick={()=>document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})}>Explorar colección <ArrowRight size={17}/></button></div><img src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85" alt="Montañas"/></section><section id="catalog" className="catalog"><header><div><small>EQUIPO ESENCIAL</small><h2>Listos para el próximo desvío.</h2></div><button onClick={()=>setOpen(true)}><ShoppingBag size={16}/> Bolsa <b>{count}</b></button></header><div className="pills">{["Todo","Abrigos","Equipamiento","Calzado"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="products">{products.filter(x=>filter==="Todo"||x.cat===filter).map(x=><article key={x.id}><div><img src={x.img} alt={x.name}/><button className={saved.includes(x.id)?"saved":""} onClick={()=>setSaved(s=>s.includes(x.id)?s.filter(id=>id!==x.id):[...s,x.id])} aria-label={`Guardar ${x.name}`}><Heart size={18} fill={saved.includes(x.id)?"currentColor":"none"}/></button></div><small>{x.cat}</small><h3>{x.name} <b>US$ {x.price}</b></h3><button onClick={()=>change(x.id,1)}>Agregar a la bolsa <Plus size={15}/></button></article>)}</div></section></main>
  {open&&<div className="cart-layer" onClick={()=>setOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><header><div><small>TU SELECCIÓN</small><h2>Bolsa <span>{count}</span></h2></div><button onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header>{checkout?<div className="cart-success"><i><Check size={25}/></i><h3>Pedido confirmado</h3><p>Esta es una demostración: no se realizó ningún cobro.</p><button onClick={()=>{setCheckout(false);setCart({});setOpen(false)}}>Volver a la tienda</button></div>:count===0?<div className="cart-empty"><ShoppingBag size={30}/><h3>Tu bolsa está vacía</h3><p>Elegí algo preparado para la próxima aventura.</p><button onClick={()=>setOpen(false)}>Explorar productos</button></div>:<><div className="cart-lines">{products.filter(p=>cart[p.id]).map(p=><article key={p.id}><img src={p.img} alt=""/><div><small>{p.cat}</small><b>{p.name}</b><span>US$ {p.price}</span><div><button onClick={()=>change(p.id,-1)}>−</button><b>{cart[p.id]}</b><button onClick={()=>change(p.id,1)}>+</button></div></div><button onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}>Eliminar</button></article>)}</div><footer><p>Envío <b>Gratis</b></p><p>Subtotal <b>US$ {subtotal}</b></p><button onClick={()=>setCheckout(true)}>Finalizar compra <ArrowRight size={16}/></button><small>Checkout seguro · Demo sin cobros reales</small></footer></>}</aside></div>}</Shell>
};

const Analytics=()=>{
  const bars=[44,63,48,72,58,82,75,94,68,87,76,98];
  const [period,setPeriod]=useState(30),[selected,setSelected]=useState("");
  const ratio=period===30?1:.72;
  return <Shell kind="analytics"><main className="dash"><header className="page-head"><div><small>LUNES, 27 JUL</small><h1>Buen día, Lucio.</h1><p>Tu negocio creció un {period===30?"18,4":"7,2"}% en el período.</p></div><button onClick={()=>setPeriod(p=>p===30?7:30)}><CalendarDays size={15}/> Últimos {period} días <ChevronDown size={14}/></button></header><section className="metrics">{[["Ingresos netos",period===30?"$84.240":"$21.680","+18,4%"],["Pedidos",period===30?"1.429":"382","+12,1%"],["Ticket promedio","$58,95","+4,2%"],["Devoluciones","2,4%","-0,8%"]].map(x=><article key={x[0]}><span>{x[0]}<MoreHorizontal size={16}/></span><b>{x[1]}</b><small>{x[2]} <em>vs. período anterior</em></small></article>)}</section><section className="data-grid"><article className="chart"><header><div><span>Ingresos</span><b>{period===30?"$84.240":"$21.680"}</b></div><small><i/> Este período</small></header><div className="bars">{bars.map((h,i)=><i style={{height:`${h*ratio}%`}} key={i}/>)}</div></article><article className="channels"><b>Canales de venta</b><div className="donut"><span>{period===30?"1.429":"382"}<small>ventas</small></span></div>{[["Tienda online","62%"],["Marketplace","24%"],["Retail","14%"]].map(x=><p key={x[0]}>{x[0]}<b>{x[1]}</b></p>)}</article></section><section className="activity"><header><b>Actividad reciente</b><small>{selected?`Pedido ${selected} seleccionado`:"Seleccioná un pedido para inspeccionarlo"}</small></header>{[["#1048","Camila Rossi","$142,00","Completado"],["#1047","Mateo Silva","$89,50","Procesando"],["#1046","Julia Gómez","$274,20","Completado"]].map(x=><div className={selected===x[0]?"selected":""} onClick={()=>setSelected(x[0])} key={x[0]}>{x.map(y=><span key={y}>{y}</span>)}</div>)}</section></main></Shell>
};

const Management=()=>{
  const [selected,setSelected]=useState(""),[modal,setModal]=useState(false),[title,setTitle]=useState(""),[custom,setCustom]=useState<string[]>([]),[view,setView]=useState("Board");
  const cols=[["POR HACER",["Onboarding de comercios",...custom]],["EN CURSO",["Sistema de diseño v3","Migración de infraestructura"]],["EN REVISIÓN",["Nueva experiencia de checkout"]],["LISTO",["Nueva página de precios"]]];
  const create=()=>{if(title.trim()){setCustom(c=>[...c,title.trim()]);setTitle("");setModal(false)}};
  return <Shell kind="management"><main className="orbit"><aside><button><Search size={16}/> Buscar <kbd>⌘ K</kbd></button><small>WORKSPACE</small><button><LayoutDashboard size={16}/> Overview</button><button className="on"><Package size={16}/> Proyectos</button><button><Users size={16}/> Equipo</button><small>FAVORITOS</small><button><i/> Plataforma web</button><button><i/> Mobile app</button></aside><section><header className="page-head"><div><small>PROYECTOS / PRODUCTO</small><h1>Plataforma web</h1><p>{selected?`Seleccionaste “${selected}”`:"Todo lo necesario para llegar a producción."}</p></div><button onClick={()=>setModal(true)}><Plus size={15}/> Nueva tarea</button></header><nav className="views">{["Board","Lista","Timeline"].map(x=><button className={view===x?"on":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</nav>{view==="Board"?<div className="kanban">{cols.map((col,ci)=><div key={col[0] as string}><header><b><i/>{col[0]}</b><span>{col[1].length}</span></header>{(col[1] as string[]).map((task,ti)=><button className={selected===task?"selected":""} onClick={()=>setSelected(selected===task?"":task)} key={task}><small>{["Growth","Diseño","Dev","Producto"][ci]}</small><h3>{task}</h3><div className="progress"><i style={{width:`${40+ti*22+ci*12}%`}}/></div><footer><span><Clock3 size={12}/> {ci+27} Jul</span><b>LC</b></footer></button>)}<button onClick={()=>setModal(true)} className="add"><Plus size={14}/> Agregar tarea</button></div>)}</div>:<div className={`alternative-view ${view.toLowerCase()}`}><BarChart3 size={25}/><h3>Vista {view}</h3><p>{view==="Lista"?"Priorizá, buscá y editá todas las tareas en una tabla compacta.":"Visualizá dependencias y fechas de entrega del proyecto."}</p>{cols.flatMap(c=>c[1]).map((task,i)=><div key={task}><span>PLAT-{128+i}</span><b>{task}</b><em>{i%2?"En curso":"Pendiente"}</em></div>)}</div>}</section></main>{modal&&<div className="modal-layer" onClick={()=>setModal(false)}><form className="demo-modal" onSubmit={e=>{e.preventDefault();create()}} onClick={e=>e.stopPropagation()}><small>NUEVA TAREA</small><h2>¿Qué hay que hacer?</h2><label>Título<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Revisar flujo de checkout"/></label><label>Responsable<select><option>Lucio Carrera</option><option>Sofía Vidal</option></select></label><div><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button disabled={!title.trim()}>Crear tarea</button></div></form></div>}</Shell>
};

const Booking=()=>{
  const [guests,setGuests]=useState(2),[time,setTime]=useState("21:00"),[done,setDone]=useState(false);
  return <Shell kind="booking"><main className="mesa"><section><img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=85" alt="Restaurante"/><div><small>COCINA DE ESTACIÓN · BUENOS AIRES</small><h1>Una mesa.<br/>Una pausa.<br/>Algo para recordar.</h1><p>Producto, fuego y tiempo. Lo demás sobra.</p></div></section><section className="reserve">{done?<div className="confirmed"><i><Check size={28}/></i><small>RESERVA CONFIRMADA</small><h2>Nos vemos el viernes.</h2><p>Mesa para {guests} a las {time}. Enviamos los detalles a tu correo.</p><b>31 <span>JUL<br/>2026</span></b><button onClick={()=>setDone(false)}>Modificar reserva</button></div>:<><small>RESERVAS</small><h2>Tu mesa te espera.</h2><p>Elegí cuándo venir. Nosotros hacemos el resto.</p><label>FECHA<button><CalendarDays size={17}/> Vie, 31 de julio <ChevronDown size={14}/></button></label><label>PERSONAS<div className="stepper"><button onClick={()=>setGuests(Math.max(1,guests-1))}>−</button><b>{guests} personas</b><button onClick={()=>setGuests(guests+1)}>+</button></div></label><label>HORARIO<div className="times">{["19:30","20:00","20:30","21:00","21:30","22:00"].map(x=><button className={time===x?"on":""} onClick={()=>setTime(x)} key={x}>{x}</button>)}</div></label><button className="confirm" onClick={()=>setDone(true)}>Confirmar reserva <ArrowRight size={17}/></button></>}</section></main></Shell>
};

const Automation=()=>{
  const [running,setRunning]=useState(true),[runs,setRuns]=useState(1248),[zoom,setZoom]=useState(85),[panel,setPanel]=useState("Workflows"),[modal,setModal]=useState(false),[workflow,setWorkflow]=useState("");
  return <Shell kind="automation"><main className="flow"><aside><button onClick={()=>setModal(true)} className="new"><Plus size={16}/> Nuevo workflow</button>{[["Workflows",Zap],["Agentes IA",WandSparkles],["Ejecuciones",Activity],["Conexiones",Settings2]].map(([label,I])=>{const Icon=I as typeof Zap;return <button className={panel===label?"on":""} onClick={()=>setPanel(label as string)} key={label as string}><Icon size={16}/>{label as string}</button>})}<div><small>USO DEL MES</small><i><b/></i><strong>6.842 / 10.000 runs</strong></div></aside><section><header className="flow-head"><div><small>{running?"● EN PRODUCCIÓN":"○ WORKFLOW PAUSADO"}</small><h1>{workflow||"Revenue intelligence"}</h1><p>{panel==="Workflows"?"Califica oportunidades y prepara el siguiente paso automáticamente.":`Explorando la sección ${panel}.`}</p></div><div><button onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?"Pausar":"Activar"}</button><button onClick={()=>{setRuns(runs+1);setRunning(true)}}><Play size={15}/> Ejecutar ahora</button></div></header><div className="flow-metrics">{[["Ejecuciones",runs.toLocaleString("es-AR"),"+14,2%"],["Tasa de éxito","98,7%","+1,1%"],["Tiempo ahorrado","74 h","este mes"],["Costo por run","$0,018","-8,4%"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><section className="canvas"><header>Workflow <span><button onClick={()=>setZoom(z=>Math.max(65,z-10))}>−</button>{zoom}%<button onClick={()=>setZoom(z=>Math.min(115,z+10))}>+</button></span></header><div className="nodes" style={{transform:`scale(${zoom/85})`}}>{[["TRIGGER","Nuevo lead en CRM","HubSpot",Zap],["AGENTE IA","Investigar la cuenta","GPT-5 · Web search",Sparkles],["ACCIÓN","Crear briefing","Notion",Send],["ACCIÓN","Avisar al equipo","Slack",MessageCircle]].map((x,i)=>{const Icon=x[3] as typeof Zap;return <Fragment key={x[1] as string}><article><Icon size={18}/><div><small>{x[0] as string}</small><b>{x[1] as string}</b><em>{x[2] as string}</em></div><CheckCircle2 size={15}/></article>{i<3&&<i className="line"/>}</Fragment>})}</div></section></section></main>{modal&&<div className="modal-layer" onClick={()=>setModal(false)}><form className="demo-modal" onSubmit={e=>{e.preventDefault();if(workflow.trim())setModal(false)}} onClick={e=>e.stopPropagation()}><small>NUEVO WORKFLOW</small><h2>¿Qué querés automatizar?</h2><label>Nombre<input autoFocus value={workflow} onChange={e=>setWorkflow(e.target.value)} placeholder="Ej. Enriquecer nuevos contactos"/></label><label>Inicio<select><option>Empezar desde cero</option><option>Usar plantilla de ventas</option></select></label><div><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button disabled={!workflow.trim()}>Crear workflow</button></div></form></div>}</Shell>
};

const Social=()=>{
 const [liked,setLiked]=useState(false),[modal,setModal]=useState(false),[network,setNetwork]=useState("Todos"),[post,setPost]=useState(""),[scheduled,setScheduled]=useState<string[]>([]);
 const publish=()=>{if(post.trim()){setScheduled(s=>[...s,post.trim()]);setPost("");setModal(false)}};
 return <Shell kind="social"><main className="beacon"><header className="page-head"><div><small>CONTENT STUDIO</small><h1>Todo lo que publicás.<br/>Una sola vista.</h1></div><button onClick={()=>setModal(true)}><Plus size={15}/> Crear contenido</button></header><section className="social-cards"><article className="audience"><span>Audiencia total</span><b>248.6K</b><small><TrendingUp size={13}/> 12.8% este mes</small><div>{[22,34,30,46,40,55,48,66,58,72,64,84,78,92].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></article><article className="reach">{[["Alcance","1.8M","+24.6%"],["Interacciones","94.2K","+18.1%"],["Engagement","5.2%","+0.8%"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</article><article className="best"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=700&q=80" alt="Estudio"/><div><small>MEJOR POST · INSTAGRAM</small><p>Las ideas crecen cuando encuentran espacio.</p><button className={liked?"liked":""} onClick={()=>setLiked(!liked)}><Heart size={15} fill={liked?"currentColor":"none"}/> {liked?"12.5K":"12.4K"}</button></div></article></section><section className="calendar"><header><div><h2>Próximas publicaciones</h2><p>Esta semana · {8+scheduled.length} contenidos programados</p></div><div className="network-filter">{["Todos","Instagram","LinkedIn"].map(x=><button className={network===x?"on":""} onClick={()=>setNetwork(x)} key={x}>{x}</button>)}</div></header><div>{["LUN 27","MAR 28","MIÉ 29","JUE 30","VIE 31"].map((d,i)=><section key={d}><small>{d}</small>{i<3?<article><span>{["09:30","12:15","18:00"][i]}</span><i/><b>{["Behind the scenes","5 ideas para diseñar mejor","Weekly product note"][i]}</b><em>{i===1?"LinkedIn":"Instagram"}</em></article>:i===3&&scheduled.length?<article><span>10:00</span><i/><b>{scheduled[scheduled.length-1]}</b><em>{network==="Todos"?"Instagram":network}</em></article>:<button onClick={()=>setModal(true)}><Plus size={16}/></button>}</section>)}</div></section></main>{modal&&<div className="modal-layer" onClick={()=>setModal(false)}><form className="demo-modal social-compose" onSubmit={e=>{e.preventDefault();publish()}} onClick={e=>e.stopPropagation()}><small>NUEVO CONTENIDO</small><h2>Prepará tu próxima idea.</h2><label>Texto<textarea autoFocus value={post} onChange={e=>setPost(e.target.value)} placeholder="¿Qué querés compartir?"/></label><label>Canal<select value={network==="Todos"?"Instagram":network} onChange={e=>setNetwork(e.target.value)}><option>Instagram</option><option>LinkedIn</option></select></label><div><button type="button" onClick={()=>setModal(false)}>Guardar borrador</button><button disabled={!post.trim()}>Programar post</button></div></form></div>}</Shell>
};

export const DemoExperience=({kind}:{kind:Kind})=>kind==="commerce"?<Commerce/>:kind==="analytics"?<Analytics/>:kind==="management"?<Management/>:kind==="booking"?<Booking/>:kind==="automation"?<Automation/>:<Social/>;
